var searchData=
[
  ['statistics_20functions',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['support_20functions',['Support Functions',['../group__group_support.html',1,'']]],
  ['system_20ahb_20and_20apb_20busses_20clocks_20configuration_20functions',['System AHB and APB busses clocks configuration functions',['../group___r_c_c___group2.html',1,'']]],
  ['shift_20control_20synchronisation_20functions',['Shift control synchronisation functions',['../group___r_t_c___group12.html',1,'']]],
  ['sdio',['SDIO',['../group___s_d_i_o.html',1,'']]],
  ['sdio_5fbus_5fwide',['SDIO_Bus_Wide',['../group___s_d_i_o___bus___wide.html',1,'']]],
  ['sdio_5fclock_5fbypass',['SDIO_Clock_Bypass',['../group___s_d_i_o___clock___bypass.html',1,'']]],
  ['sdio_5fclock_5fedge',['SDIO_Clock_Edge',['../group___s_d_i_o___clock___edge.html',1,'']]],
  ['sdio_5fclock_5fpower_5fsave',['SDIO_Clock_Power_Save',['../group___s_d_i_o___clock___power___save.html',1,'']]],
  ['sdio_5fcommand_5findex',['SDIO_Command_Index',['../group___s_d_i_o___command___index.html',1,'']]],
  ['sdio_5fcpsm_5fstate',['SDIO_CPSM_State',['../group___s_d_i_o___c_p_s_m___state.html',1,'']]],
  ['sdio_5fdata_5fblock_5fsize',['SDIO_Data_Block_Size',['../group___s_d_i_o___data___block___size.html',1,'']]],
  ['sdio_5fdata_5flength',['SDIO_Data_Length',['../group___s_d_i_o___data___length.html',1,'']]],
  ['sdio_5fdpsm_5fstate',['SDIO_DPSM_State',['../group___s_d_i_o___d_p_s_m___state.html',1,'']]],
  ['sdio_5fexported_5fconstants',['SDIO_Exported_Constants',['../group___s_d_i_o___exported___constants.html',1,'']]],
  ['sdio_5fflags',['SDIO_Flags',['../group___s_d_i_o___flags.html',1,'']]],
  ['sdio_20io_20cards_20mode_20management_20functions',['SDIO IO Cards mode management functions',['../group___s_d_i_o___group4.html',1,'']]],
  ['sdio_5fhardware_5fflow_5fcontrol',['SDIO_Hardware_Flow_Control',['../group___s_d_i_o___hardware___flow___control.html',1,'']]],
  ['sdio_5finterrupt_5fsources',['SDIO_Interrupt_sources',['../group___s_d_i_o___interrupt__sources.html',1,'']]],
  ['sdio_5fpower_5fstate',['SDIO_Power_State',['../group___s_d_i_o___power___state.html',1,'']]],
  ['sdio_5fprivate_5ffunctions',['SDIO_Private_Functions',['../group___s_d_i_o___private___functions.html',1,'']]],
  ['sdio_5fread_5fwait_5fmode',['SDIO_Read_Wait_Mode',['../group___s_d_i_o___read___wait___mode.html',1,'']]],
  ['sdio_5fresponse_5fregisters',['SDIO_Response_Registers',['../group___s_d_i_o___response___registers.html',1,'']]],
  ['sdio_5fresponse_5ftype',['SDIO_Response_Type',['../group___s_d_i_o___response___type.html',1,'']]],
  ['sdio_5ftransfer_5fdirection',['SDIO_Transfer_Direction',['../group___s_d_i_o___transfer___direction.html',1,'']]],
  ['sdio_5ftransfer_5ftype',['SDIO_Transfer_Type',['../group___s_d_i_o___transfer___type.html',1,'']]],
  ['sdio_5fwait_5finterrupt_5fstate',['SDIO_Wait_Interrupt_State',['../group___s_d_i_o___wait___interrupt___state.html',1,'']]],
  ['self_5ftest_5fselection',['Self_Test_selection',['../group___self___test__selection.html',1,'']]],
  ['signal_20convergence_20example',['Signal Convergence Example',['../group___signal_convergence.html',1,'']]],
  ['sine',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine',['Sine Cosine',['../group___sin_cos.html',1,'']]],
  ['sinecosine_20example',['SineCosine Example',['../group___sin_cos_example.html',1,'']]],
  ['spi',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_5fbaudrate_5fprescaler',['SPI_BaudRate_Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_5fclock_5fphase',['SPI_Clock_Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_5fclock_5fpolarity',['SPI_Clock_Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_5fcrc_5fpolynomial',['SPI_CRC_polynomial',['../group___s_p_i___c_r_c__polynomial.html',1,'']]],
  ['spi_5fcrc_5ftransmit_5freceive',['SPI_CRC_Transmit_Receive',['../group___s_p_i___c_r_c___transmit___receive.html',1,'']]],
  ['spi_5fdata_5fdirection',['SPI_data_direction',['../group___s_p_i__data__direction.html',1,'']]],
  ['spi_5fdata_5fsize',['SPI_data_size',['../group___s_p_i__data__size.html',1,'']]],
  ['spi_5fdirection_5ftransmit_5freceive',['SPI_direction_transmit_receive',['../group___s_p_i__direction__transmit__receive.html',1,'']]],
  ['spi_5fexported_5fconstants',['SPI_Exported_Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_5fi2s_5faudio_5ffrequency',['SPI_I2S_Audio_Frequency',['../group___s_p_i___i2_s___audio___frequency.html',1,'']]],
  ['spi_5fi2s_5fclock_5fpolarity',['SPI_I2S_Clock_Polarity',['../group___s_p_i___i2_s___clock___polarity.html',1,'']]],
  ['spi_5fi2s_5fdata_5fformat',['SPI_I2S_Data_Format',['../group___s_p_i___i2_s___data___format.html',1,'']]],
  ['spi_5fi2s_5fdma_5ftransfer_5frequests',['SPI_I2S_DMA_transfer_requests',['../group___s_p_i___i2_s___d_m_a__transfer__requests.html',1,'']]],
  ['spi_5fi2s_5fflags_5fdefinition',['SPI_I2S_flags_definition',['../group___s_p_i___i2_s__flags__definition.html',1,'']]],
  ['spi_5fi2s_5finterrupts_5fdefinition',['SPI_I2S_interrupts_definition',['../group___s_p_i___i2_s__interrupts__definition.html',1,'']]],
  ['spi_5fi2s_5flegacy',['SPI_I2S_Legacy',['../group___s_p_i___i2_s___legacy.html',1,'']]],
  ['spi_5fi2s_5fmclk_5foutput',['SPI_I2S_MCLK_Output',['../group___s_p_i___i2_s___m_c_l_k___output.html',1,'']]],
  ['spi_5fi2s_5fmode',['SPI_I2S_Mode',['../group___s_p_i___i2_s___mode.html',1,'']]],
  ['spi_5fi2s_5fstandard',['SPI_I2S_Standard',['../group___s_p_i___i2_s___standard.html',1,'']]],
  ['spi_5fmode',['SPI_mode',['../group___s_p_i__mode.html',1,'']]],
  ['spi_5fmsb_5flsb_5ftransmission',['SPI_MSB_LSB_transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_5fnss_5finternal_5fsoftware_5fmanagement',['SPI_NSS_internal_software_management',['../group___s_p_i___n_s_s__internal__software__management.html',1,'']]],
  ['spi_5fprivate_5ffunctions',['SPI_Private_Functions',['../group___s_p_i___private___functions.html',1,'']]],
  ['spi_5fserial_5finterface_5fmode_5fselection',['SPI_Serial_Interface_Mode_selection',['../group___s_p_i___serial___interface___mode__selection.html',1,'']]],
  ['spi_5fslave_5fselect_5fmanagement',['SPI_Slave_Select_management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['square_20root',['Square Root',['../group___s_q_r_t.html',1,'']]],
  ['standard_20deviation',['Standard deviation',['../group___s_t_d.html',1,'']]],
  ['stm32f4_5fdiscovery',['STM32F4_DISCOVERY',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y.html',1,'']]],
  ['stm32f4_5fdiscovery_5fcc2500_5fexported_5ffunctions',['STM32F4_DISCOVERY_CC2500_Exported_Functions',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___c_c2500___exported___functions.html',1,'']]],
  ['stm32f4_5fdiscovery_5fcc2500_5fprivate_5fdefines',['STM32F4_DISCOVERY_CC2500_Private_Defines',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___c_c2500___private___defines.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl',['STM32F4_DISCOVERY_LIS302DL',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fexported_5fconstants',['STM32F4_DISCOVERY_LIS302DL_Exported_Constants',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___exported___constants.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fexported_5ffunctions',['STM32F4_DISCOVERY_LIS302DL_Exported_Functions',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___exported___functions.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fexported_5fmacros',['STM32F4_DISCOVERY_LIS302DL_Exported_Macros',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___exported___macros.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fexported_5ftypes',['STM32F4_DISCOVERY_LIS302DL_Exported_Types',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___exported___types.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5fdefines',['STM32F4_DISCOVERY_LIS302DL_Private_Defines',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___defines.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5ffunctionprototypes',['STM32F4_DISCOVERY_LIS302DL_Private_FunctionPrototypes',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___function_prototypes.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5ffunctions',['STM32F4_DISCOVERY_LIS302DL_Private_Functions',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___functions.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5fmacros',['STM32F4_DISCOVERY_LIS302DL_Private_Macros',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___macros.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5ftypesdefinitions',['STM32F4_DISCOVERY_LIS302DL_Private_TypesDefinitions',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___types_definitions.html',1,'']]],
  ['stm32f4_5fdiscovery_5flis302dl_5fprivate_5fvariables',['STM32F4_DISCOVERY_LIS302DL_Private_Variables',['../group___s_t_m32_f4___d_i_s_c_o_v_e_r_y___l_i_s302_d_l___private___variables.html',1,'']]],
  ['stm32f4xx',['Stm32f4xx',['../group__stm32f4xx.html',1,'']]],
  ['stm32f4xx_5fstdperiph_5fdriver',['STM32F4xx_StdPeriph_Driver',['../group___s_t_m32_f4xx___std_periph___driver.html',1,'']]],
  ['stm32f4xx_5fsystem',['Stm32f4xx_system',['../group__stm32f4xx__system.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5fconstants',['STM32F4xx_System_Exported_Constants',['../group___s_t_m32_f4xx___system___exported___constants.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5ffunctions',['STM32F4xx_System_Exported_Functions',['../group___s_t_m32_f4xx___system___exported___functions.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5fmacros',['STM32F4xx_System_Exported_Macros',['../group___s_t_m32_f4xx___system___exported___macros.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5ftypes',['STM32F4xx_System_Exported_types',['../group___s_t_m32_f4xx___system___exported__types.html',1,'']]],
  ['stm32f4xx_5fsystem_5fincludes',['STM32F4xx_System_Includes',['../group___s_t_m32_f4xx___system___includes.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5fdefines',['STM32F4xx_System_Private_Defines',['../group___s_t_m32_f4xx___system___private___defines.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5ffunctionprototypes',['STM32F4xx_System_Private_FunctionPrototypes',['../group___s_t_m32_f4xx___system___private___function_prototypes.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5ffunctions',['STM32F4xx_System_Private_Functions',['../group___s_t_m32_f4xx___system___private___functions.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5fincludes',['STM32F4xx_System_Private_Includes',['../group___s_t_m32_f4xx___system___private___includes.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5fmacros',['STM32F4xx_System_Private_Macros',['../group___s_t_m32_f4xx___system___private___macros.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5ftypesdefinitions',['STM32F4xx_System_Private_TypesDefinitions',['../group___s_t_m32_f4xx___system___private___types_definitions.html',1,'']]],
  ['stm32f4xx_5fsystem_5fprivate_5fvariables',['STM32F4xx_System_Private_Variables',['../group___s_t_m32_f4xx___system___private___variables.html',1,'']]],
  ['structs',['Structs',['../group___structs.html',1,'']]],
  ['syscfg',['SYSCFG',['../group___s_y_s_c_f_g.html',1,'']]],
  ['syscfg_5fethernet_5fmedia_5finterface',['SYSCFG_ETHERNET_Media_Interface',['../group___s_y_s_c_f_g___e_t_h_e_r_n_e_t___media___interface.html',1,'']]],
  ['syscfg_5fexported_5fconstants',['SYSCFG_Exported_Constants',['../group___s_y_s_c_f_g___exported___constants.html',1,'']]],
  ['syscfg_5fexti_5fpin_5fsources',['SYSCFG_EXTI_Pin_Sources',['../group___s_y_s_c_f_g___e_x_t_i___pin___sources.html',1,'']]],
  ['syscfg_5fexti_5fport_5fsources',['SYSCFG_EXTI_Port_Sources',['../group___s_y_s_c_f_g___e_x_t_i___port___sources.html',1,'']]],
  ['syscfg_5fmemory_5fremap_5fconfig',['SYSCFG_Memory_Remap_Config',['../group___s_y_s_c_f_g___memory___remap___config.html',1,'']]],
  ['syscfg_5fprivate_5ffunctions',['SYSCFG_Private_Functions',['../group___s_y_s_c_f_g___private___functions.html',1,'']]],
  ['synchronization_20management_20functions',['Synchronization management functions',['../group___t_i_m___group7.html',1,'']]],
  ['specific_20interface_20management_20functions',['Specific interface management functions',['../group___t_i_m___group8.html',1,'']]],
  ['specific_20remapping_20management_20function',['Specific remapping management function',['../group___t_i_m___group9.html',1,'']]],
  ['smartcard_20mode_20functions',['Smartcard mode functions',['../group___u_s_a_r_t___group6.html',1,'']]]
];
